import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Sidebar from '@/components/General/Sidebar';
import Header from '@/components/General/Header';

export const sourceCodePro = localFont({
	src: './fonts/SourceCodePro-VariableFont_wght.ttf',
	variable: '--font-source-code-pro',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${sourceCodePro.variable} background-gradient font-mono flex`}
			>
				<Header />
				<Sidebar />
				<div className='ml-64 mt-24 mr-32'>{children}</div>
			</body>
		</html>
	);
}
