import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Sidebar from '@/components/General/Sidebar';

export const sourceCodePro = localFont({
	src: './fonts/SourceCodePro-VariableFont_wght.ttf',
	variable: '--font-source-code-pro',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${sourceCodePro.variable} bg-global-background font-mono flex`}
			>
				<Sidebar />
				<div className='pl-32 grid grid-cols-10'>
					<div className='col-start-2 col-end-9 mt-24'>
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
